Repository AY2425S1-CS2103-F10-1/tp, pull requests merged in 2024-11, with the labels that each got.

#123 Fix Negative Quantity/Price bug
  src/main/java/seedu/address/model/goodsreceipt/GoodsReceipt.java
  src/main/java/seedu/address/storage/CsvGoodsStorage.java
  src/test/java/seedu/address/model/goodsreceipt/GoodsReceiptTest.java
  src/test/java/seedu/address/storage/CsvGoodsStorageTest.java
Labels: type.Bug, priority.Low, severity.Low

#126 Fix addGood bug
  src/main/java/seedu/address/logic/commands/AddGoodsCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/goodsreceipt/exceptions/IllegalSupplierNameException.java
  src/test/java/seedu/address/logic/commands/ListGoodsCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/CsvGoodsStorageTest.java
  src/test/java/seedu/address/testutil/GoodsReceiptBuilder.java
  src/test/java/seedu/address/testutil/TypicalGoods.java
Labels: type.Bug, priority.High, severity.High

#140 Change phone number length to be exactly 8 digits long
  src/main/java/seedu/address/model/person/Phone.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Bug, severity.Low, alpha-bug

#130 Add missing unit tests
  src/main/java/seedu/address/logic/commands/AddGoodsCommand.java
  src/test/java/seedu/address/logic/commands/AddGoodsCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteGoodsCommandTest.java
  src/test/java/seedu/address/logic/parser/AddGoodsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteGoodCommandParserTest.java
  src/test/java/seedu/address/testutil/GoodsReceiptBuilder.java
Labels: type.Enhancement, priority.Medium, severity.Low

#132 Change color of item depending on delivery status
  src/main/java/seedu/address/ui/GoodsCard.java
  src/main/resources/view/DarkTheme.css
Labels: priority.Low, alpha-bug

#136 Add adjustable divider to resize result box
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low, alpha-bug

#129 Display only pending goods on startup
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/goodsreceipt/DeliveredPredicate.java
  src/test/java/seedu/address/model/goodsreceipt/DeliveredPredicateTest.java
Labels: type.Bug, priority.Low, severity.Low

#144 Add draggable ui and goods name color to features in UG
  docs/UserGuide.md
  docs/images/DraggableUi.png
  docs/images/GoodsNameColorUi.png
Labels: type.Task, priority.Medium

#127 Add Sample Goods to application
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CsvGoodsStorage.java
  src/test/java/seedu/address/storage/CsvGoodsStorageTest.java
Labels: type.Task, priority.Low, severity.Low

#148 Fix documentation styling errors
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Enhancement, type.Bug

#152 Update Ui class diagram image
  docs/images/UiClassDiagram.png
Labels: type.Bug, priority.Low

#156 Remove duplicate test file
  src/test/java/seedu/address/logic/commands/AddGoodsCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddGoodsCommandParserTest.java
Labels: type.Bug

#164 Fix delete contact bug
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Bug, priority.High, severity.High

#163 Fix arrival date ordering bug
  src/main/java/seedu/address/logic/parser/AddGoodsCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/goodsreceipt/Date.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
Labels: priority.Medium, alpha-bug

#168 Automatic marking of "Delivered" Goods
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReceiptLog.java
  src/main/java/seedu/address/model/goodsreceipt/Date.java
  src/main/java/seedu/address/model/goodsreceipt/GoodsReceipt.java
  src/main/java/seedu/address/model/goodsreceipt/UniqueGoodsReceiptList.java
  src/main/java/seedu/address/storage/CsvGoodsStorage.java
  src/main/java/seedu/address/storage/GoodsStorage.java
Labels: priority.High, severity.Medium, alpha-bug

#170 Fix Sample Person Bug
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Bug, priority.High, severity.High, alpha-bug

#161 UI enhancements
  docs/UserGuide.md
  docs/images/DeliveryStatusColorUi.png
  docs/images/DraggableUi.png
  docs/images/GoodsNameColorUi.png
  src/main/java/seedu/address/ui/GoodsCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GoodsListCard.fxml
Labels: type.Enhancement, priority.Low

#167 Update DG and UG about Storage and CSV
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
Labels: type.Task, priority.Low, severity.Low

#172 Fix DG formatting for UC4
  docs/DeveloperGuide.md
Labels: type.Bug, severity.Low

#253 Update window title
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, priority.Low, severity.Low

#255 Raise error if Preamble is given with viewgoods
  src/main/java/seedu/address/logic/parser/ListGoodsCommandParser.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ListGoodsCommandParserTest.java
Labels: type.Bug, priority.Low, severity.Low

#254 Resolve DateTime issues
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/goodsreceipt/Date.java
  src/test/java/seedu/address/model/goodsreceipt/DateTest.java
  src/test/java/seedu/address/storage/CsvConvertersTest.java
  src/test/java/seedu/address/storage/CsvGoodsStorageTest.java
  src/test/java/seedu/address/testutil/GoodsReceiptBuilder.java
Labels: type.Bug, priority.Medium, severity.Medium

#262 Update command information in UG
  docs/UserGuide.md
  docs/images/findAlexLifeStyleResult.png
  docs/team/jialegitgud.md
Labels: type.Enhancement, priority.Low

#270 Uer Guide fix
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/old-Ui.png
  docs/team/stephaneleong.md
Labels: type.Enhancement, priority.Medium, severity.Medium

#275 Final Cleanup for UG/DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/GoodsClassDiagram.puml
Labels: type.Enhancement, priority.Low, severity.Low

#279 Add page breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Bug, severity.Low
