Repository AY2425S1-CS2103-F10-1/tp, pull requests merged in 2024-10, with the labels that each got.

#17 Add Jiale's Photo
  .gitignore
  docs/images/jialegitgud.png
Labels: type.Task

#18 Update AboutUs Page (Jiale)
  docs/AboutUs.md
  docs/team/jialegitgud.md
Labels: type.Task

#30 Add NFRs and glossary terms
  docs/AboutUs.md
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#37 Rename Jasper photo
  docs/AboutUs.md
  docs/images/ossaris56.png
Labels: type.Bug, priority.Low, severity.Low

#28 Update use cases
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#12 Add Goods Class
  .gitignore
  src/main/java/seedu/address/logic/commands/AddGoodsCommand.java
  src/main/java/seedu/address/logic/parser/AddGoodsCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/goods/Date.java
  src/main/java/seedu/address/model/goods/Goods.java
  src/main/java/seedu/address/model/goods/GoodsCategories.java
  src/main/java/seedu/address/model/goods/GoodsName.java
  src/main/java/seedu/address/model/goods/GoodsUtil.java
Labels: type.Task, priority.Medium

#47 Refactor UI
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#49 Add Product Scope and User Stories
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#54 Add Test Coverage for Goods
  src/main/java/seedu/address/model/goods/Date.java
  src/main/java/seedu/address/model/goods/Goods.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/goods/DateTest.java
  src/test/java/seedu/address/model/goods/GoodsNameTest.java
  src/test/java/seedu/address/model/goods/GoodsTest.java
  src/test/java/seedu/address/model/goods/GoodsUtilTest.java
  src/test/java/seedu/address/testutil/GoodsTestUtil.java
Labels: type.Enhancement

#56 Adapt Help Menu
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug

#66 Add ViewGoodsCommand support
  src/main/java/seedu/address/logic/commands/ListGoodsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ListGoodsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/goods/Goods.java
  src/main/java/seedu/address/model/goodsReceipt/CategoryPredicate.java
  src/main/java/seedu/address/model/goodsReceipt/GoodsNamePredicate.java
  src/main/java/seedu/address/model/goodsReceipt/SupplierNamePredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListGoodsCommandTest.java
  src/test/java/seedu/address/logic/parser/ListGoodsCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/goods/GoodsTest.java
  src/test/java/seedu/address/model/goodsReceipt/GoodsNamePredicateTest.java
  src/test/java/seedu/address/model/goodsReceipt/SupplierNamePredicateTest.java
Labels: type.Task, priority.Medium

#69 Enable Assertions
  build.gradle
Labels: type.Enhancement

#81 Remove [Email] references
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Bug, severity.Low

#85 Add View Goods and UI Integration
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteGoodsCommand.java
  src/main/java/seedu/address/logic/commands/ListGoodsCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteGoodsCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/goodsreceipt/GoodsReceipt.java
  src/main/java/seedu/address/ui/GoodsCard.java
  src/main/java/seedu/address/ui/GoodsListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/GoodsListCard.fxml
  src/main/resources/view/GoodsListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ListGoodsCommandTest.java
Labels: type.Task, priority.High

#92 Add missing implementation for CategoryPredicate
  src/main/java/seedu/address/model/goodsreceipt/CategoryPredicate.java
Labels: type.Bug, priority.High, severity.High

#95 Add assertions and logging
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReceiptLog.java
  src/main/java/seedu/address/model/goodsreceipt/UniqueGoodsReceiptList.java
Labels: priority.Low

#99 Add clear command sequence diagram
  docs/diagrams/ClearSequenceDiagram.puml
Labels: type.Task

#109 Add GoodsListPanel and GoodsCard to UI Class Diagram
  docs/diagrams/UiClassDiagram.puml
Labels: priority.Low
